### ISSUE TITLE
Spatial_Information_Fn() errors

### ISSUE THREAD

**Issue by dvarkey** [nwfsc-assess/geostatistical_delta-GLMM#26]
Trying to run singlespecies example and west coast annual example https://github.com/James-Thorson/VAST/tree/master/examples

Error at the following line: Spatial_List = SpatialDeltaGLMM::Spatial_Information_Fn(). Cannot run the code further for the examples.

Error is the following: 
Num=99 Current_Best=765121 New=798064.5
Num=100 Current_Best=765121 New=777834.5
Calculated and saved to C:/Users/varkeyd/Documents/vast/VAST_output_2017-11-30_LingCod_nx=250//Kmeans-250.RData
Error in RANN::nn2(data = loc_grid, query = loc_i, k = 1) : 
  Query and data tables must have same dimensions

**Comment by bethphillips** [comment]
I'm getting the same error when running West_Coast_Annual_example_2017, VAST--multispecies_example, and VAST--singlespecies_example.

Is there something that has changed about the datasets being used for the examples?

**Comment by James-Thorson** [comment]
Hi there, I'm looking into this today ;)

**Comment by James-Thorson** [comment]
OK, I think I fixed it:  it was a bug I introduced when trying to clean up code in `SpatialDeltaGLMM::Spatial_Information_Fn` during my last addition of alternative projection methods.  Please try again and close the issue if fixed?

**Comment by bethphillips** [comment]
I just ran the West_Coast_Annual_example_2017 and got the same error...

Here's the printout (looks same as before):

...
Num=99 Current_Best=765121 New=798064.5
Num=100 Current_Best=765121 New=777834.5
Calculated and saved to /Users/elizabeth/.../VAST/VAST_output_2017-12-07_LingCod_nx=250//Kmeans-250.RData
Error in RANN::nn2(data = loc_grid, query = loc_i, k = 1) : 
  Query and data tables must have same dimensions

**Comment by James-Thorson** [comment]
Sorry, should have said you'll need to reinstall SpatialDeltaGLMM. Did you
try that first?

On Dec 7, 2017 11:08 AM, "bethphillips" <notifications@github.com> wrote:

I just ran the West_Coast_Annual_example_2017 and got the same error...

Here's the printout (looks same as before):

...

Num=99 Current_Best=765121 New=798064.5
Num=100 Current_Best=765121 New=777834.5
Calculated and saved to /Users/elizabeth/.../VAST/VAST_output_2017-12-07_
LingCod_nx=250//Kmeans-250.RData

Error in RANN::nn2(data = loc_grid, query = loc_i, k = 1) :
Query and data tables must have same dimensions

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nwfsc-assess/geostatistical_delta-GLMM/issues/26#issuecomment-350064389>,
or mute the thread

**Comment by bethphillips** [comment]
Yes - reinstall of latest version (3.5.0) works!

Thank you

**Comment by dvarkey** [comment]
Spatial_Information_Fn() errors solved

**Comment by dvarkey** [comment]
Thank you Jim
